data:
  dir: "/lustre/home/yangsen/database/ESMAtlas/script_for_all/txt/"
  train_prefix: [0, 1, 2, 3, 4, 5, 6, 7, 8]
  valid_prefix: [9]
  train_num: 14792651
  valid_num: 1643186
  shuffle: True
  min_len: 40
  max_len: 512

model:
  structure_track: true
  sequence_track: true
  d_time: 512
  d_model: 1024
  n_layers: 18
  n_heads: 16
  finetune_esm: False
  eps: 1.e-10

train:
  seed: 42
  do_train: true
  optim: "adamw_torch"
  adam_beta1: 0.9
  adam_beta2: 0.98
  learning_rate: 2.e-4
  lr_scheduler_type: "constant"
  weight_decay: 0.01
  warmup_steps: 1000
  per_device_train_batch_size: 24
  gradient_accumulation_steps: 2
  max_steps: 1000000
  save_total_limit: 10
  output_dir: "./save/denovo"
  overwrite_output_dir: True
  bf16: False
  fp16: True
  save_strategy: "steps"
  save_steps: 5000
  eval_strategy: "steps"
  eval_steps: 5000
  eval_accumulation_steps: 50
  per_device_eval_batch_size: 4
