data:
  struc_file: "./data/struc.txt"
  seq_file: "./data/seq.txt"

diffusion:
  T: 1000
  hybrid_loss_coeff: 0.

model:
  structure_track: true
  sequence_track: true
  finetune_esm: true
  d_time: 512
  d_model: 1536
  n_layers: 48
  n_heads: 24

train:
  seed: 42
  do_train: true
  optim: "adamw_torch"
  adam_beta1: 0.9
  adam_beta2: 0.98
  learning_rate: 2.e-5
  lr_scheduler_type: "constant"
  per_device_train_batch_size: 16
  gradient_accumulation_steps: 2
  num_train_epochs: 50
  save_total_limit: 10
  output_dir: "./save/finetune"
  overwrite_output_dir: True
  bf16: true
  fp16: false
  save_strategy: "steps"
  save_steps: 1000
  eval_strategy: "steps"
  eval_steps: 1000
  eval_accumulation_steps: 50
  per_device_eval_batch_size: 4
