data:
  dir: "./data"
  train_prefix: ["pdb"]
  valid_prefix: ["pdb"]
  train_num: 23172
  valid_num: 23172
  shuffle: True
  min_len: 40
  max_len: 512

model:
  finetune_esm: true
  d_time: 512
  d_model: 1536
  n_layers: 48
  n_heads: 24
  directional: False
  simplified_encoder: False
  eps: 1.e-10
  train_async: True

train:
  seed: 42
  do_train: true
  optim: "adamw_torch"
  adam_beta1: 0.9
  adam_beta2: 0.98
  learning_rate: 3.e-6
  lr_scheduler_type: "constant"
  per_device_train_batch_size: 12
  gradient_accumulation_steps: 2
  num_train_epochs: 200
  save_total_limit: 5
  output_dir: "./save/finetune_async_pdb"
  overwrite_output_dir: True
  bf16: True
  fp16: False
  save_strategy: "steps"
  save_steps: 10000
  eval_strategy: "steps"
  eval_steps: 10000
  eval_accumulation_steps: 50
  per_device_eval_batch_size: 4
  checkpoint: "./save/finetune_async/checkpoint-370000"
